Rickie redesign 3
Runnable/docs pull request #10
Opened 2017-01-25 01:58 UTC by rickiesherman

1: Images are now blocks, so they never are inline.
![screen shot 2017-01-24 at 5 54 35 pm](https://cloud.githubusercontent.com/assets/1011059/22274951/3338d1e4-e25e-11e6-8812-2054fff453eb.png)
![screen shot 2017-01-24 at 5 54 37 pm](https://cloud.githubusercontent.com/assets/1011059/22274952/33392c02-e25e-11e6-801b-06131f1a924b.png)

2: Search input is bigger, works better in mobile mode
![screen shot 2017-01-24 at 5 55 15 pm](https://cloud.githubusercontent.com/assets/1011059/22274966/4df59968-e25e-11e6-963c-7e6490a83178.png)
![screen shot 2017-01-24 at 5 55 22 pm](https://cloud.githubusercontent.com/assets/1011059/22274967/4df923ee-e25e-11e6-8be7-ee062681d636.png)

3: Adjusted height of sidebar in mobile width
![screen shot 2017-01-24 at 5 57 06 pm](https://cloud.githubusercontent.com/assets/1011059/22275032/a9b5e96a-e25e-11e6-91e5-77c201f5c13b.png)
![screen shot 2017-01-24 at 5 57 08 pm](https://cloud.githubusercontent.com/assets/1011059/22275033/a9b60fc6-e25e-11e6-8b16-63e34770f033.png)

4: Adds sharing functionality
![screen shot 2017-01-24 at 5 58 34 pm](https://cloud.githubusercontent.com/assets/1011059/22275049/c4d3c64a-e25e-11e6-9a26-d5007d0bf517.png)

2017-01-25 02:01 UTC, rickiesherman commented
Also: Images have a max-width of 640px and the article content has a max width of 880. That way, both are more legible.

2017-01-25 19:29 UTC, tosih commented
Can we add Facebook?

2017-01-25 22:04 UTC, taylordolan requested changes

2017-01-25 22:04 UTC, taylordolan commented on _sass/articles/article.scss
> +  a:not(.well-anchor, .share) {
This breaks the styling for normal `a` tags that don't have classes and are inside `.article` elements.

2017-01-26 01:16 UTC, rickiesherman commented on _sass/articles/article.scss
> +  a:not(.well-anchor, .share) {
I believe I got this taken care of, lmk

2017-01-30 22:56 UTC, taylordolan approved these changes

2017-01-30 23:26 UTC, merged