Adding a Footer and modifying Share component
Runnable/docs pull request #15
Opened 2017-02-01 19:39 UTC by rickiesherman

Comparison shots 

New (Full size)
---
![screen shot 2017-02-01 at 11 36 27 am](https://cloud.githubusercontent.com/assets/1011059/22523054/dc44fc12-e872-11e6-8bcf-bbe283ee8e4a.png)

Old (Full size)
---
![screen shot 2017-02-01 at 11 36 22 am](https://cloud.githubusercontent.com/assets/1011059/22523127/11d7ecfe-e873-11e6-96b7-9e3e2277c40d.png)

Half size (Left is old, Right is new)
---
![screen shot 2017-02-01 at 11 36 03 am](https://cloud.githubusercontent.com/assets/1011059/22523076/ec04cd30-e872-11e6-9803-d4fd25e03df5.png)

2017-02-01 21:11 UTC, tosih commented
Looks a little funky at the bottom
![image](https://cloud.githubusercontent.com/assets/10872529/22526394/eb8cd9bc-e87f-11e6-829f-dbb243079b87.png)

2017-02-01 21:12 UTC, rickiesherman commented
@tosih i'll try to fix that, good looks

2017-02-01 21:12 UTC, tosih requested changes
Looks a little funky at the bottom

![image](https://cloud.githubusercontent.com/assets/10872529/22526394/eb8cd9bc-e87f-11e6-829f-dbb243079b87.png)

Basically the alignment of the footer objects conflicts with the sharing links.

2017-02-01 21:14 UTC, runnabro commented
Can we also add the other footer elements (the support widget + the sign up CTA)?

2017-02-01 21:15 UTC, runnabro commented on _includes/footer.html
> +      <a href="https://support.runnable.com" class="btn btn-xs link weight-strong">Get Help</a>
This link has been removed from our other footers.

2017-02-01 21:15 UTC, runnabro commented on _includes/footer.html
> +      <a href="{{ site.url }}/for/" class="btn btn-xs link weight-strong">Product</a>
We added a new docs link here.

2017-02-01 21:15 UTC, runnabro commented on _sass/components/share.scss
> +  padding: $md 0 $md 0;
This needs to be in alphabetical order

2017-02-01 21:15 UTC, runnabro commented on _sass/components/share.scss
> +  .btn-sm {
Should have an empty space between selectors.

2017-02-01 21:15 UTC, runnabro commented on _sass/components/share.scss
> +      margin: 0 auto;
This needs to be in alphabetical order

2017-02-01 21:16 UTC, runnabro commented on _sass/landing/footer.scss
> +    max-width: 520px;
Ordering

2017-02-07 01:43 UTC, tosih approved these changes

2017-02-07 01:44 UTC, tosih commented
Wait, it still looks a little off.

2017-02-07 01:44 UTC, tosih commented
![image](https://cloud.githubusercontent.com/assets/10872529/22674273/e7898438-ec93-11e6-80e5-13c0ff595256.png)

2017-02-07 17:27 UTC, rickiesherman commented
@tosih nah, I'll have a look at it

2017-02-07 17:33 UTC, rickiesherman commented
This is what it's looking like right now: 
![screen shot 2017-02-07 at 9 33 15 am](https://cloud.githubusercontent.com/assets/1011059/22703288/7ce808d6-ed18-11e6-89c3-bc79545a247b.png)

2017-02-07 18:42 UTC, tosih commented
LGTM

2017-02-11 00:11 UTC, taylordolan commented
![image](https://cloud.githubusercontent.com/assets/7440805/22848761/961cd616-efab-11e6-8a4d-2097fdde70ca.png)
at 640px

2017-02-11 00:15 UTC, taylordolan approved these changes

2017-02-11 00:16 UTC, merged