First cluster
Runnable/docs pull request #30
Opened 2017-04-05 16:51 UTC by prafulrana

2017-04-05 16:59 UTC, prafulrana commented
Question I had is... should show how to add the second repository in the same article? Or should we have a different article for it.

2017-04-05 17:25 UTC, tosih requested changes

2017-04-05 17:25 UTC, tosih commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +  ![GitHub Organization People]({{ site.baseurl }}/images/compose_config_composefile.png)
Why do all the image links have the same alt?

2017-04-05 17:27 UTC, tosih commented
I think another article to keep things short

2017-04-05 18:09 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +1. Go to your org on the Runnable.com
Missing period.

2017-04-05 18:10 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +2. Click on the "Add services" button.
Uppercase "S" in services.

2017-04-05 18:10 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +3. Find the repository where the compose file lives, and select it.
Uppercase "C" in Compose.

2017-04-05 18:14 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +6. To configure a staging environment, ensure that the staging toggled is clicked open.
> …ensure that the staging toggled is clicked open.

Is a little weird grammatically. Maybe:

> …ensure that staging is toggled on.

2017-04-05 18:17 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +9. You will now see the 2 containers running for the master branch of your repository. Note the name of the containers is the same name you gave them as in the Docker compose file.
Master branch should be default branch.

2017-04-05 18:18 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +10. Each container on Runnable gets a unique URL for external HTTP/HTTPs access.
Uppercase "S" in HTTPS

2017-04-05 18:18 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +11. Your master environment should be up! Yuo can explore the environment using the URL, Terminal and Filebrowser.
Yuo -> You

2017-04-05 18:19 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +###  Launching a Full-Stack environment for a branch
Lowercase "F" in full-stack

2017-04-05 18:20 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +2. Click on the "Add a branch button".
> Click on the "Add a branch button".

Should be:

> Click on the "Add a Branch" button.

2017-04-05 18:20 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +4. Now push a change to the repository Github.com, on an existing branch other than master.
1. Does it have to be on GitHub.com? 
2. GitHub has a uppercase "H".

2017-04-05 18:21 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +6. You can now use your branch's environment to verify or debug you and your teammates changes.
> debug you and your teammates changes.

Should be:

> debug yours and your teammate’s changes.

2017-04-05 18:22 UTC, prafulrana commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +9. You will now see the 2 containers running for the master branch of your repository. Note the name of the containers is the same name you gave them as in the Docker compose file.
but we dont support changing that right now, correct?

2017-04-05 18:25 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +6. You can now use your branch's environment to verify or debug yours and your teammates changes.
> teammates

Should be:

> teammate’s

2017-04-05 18:25 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +From compose file, it is clear that we expect to see 2 containers launch for this repository: a web container and a db container. To configure this repository on Runnable,
Uppercase "C" in compose.

2017-04-05 18:25 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +9. You will now see the 2 containers running for the master branch of your repository. Note the name of the containers is the same name you gave them as in the Docker compose file.
Right, that's why it should be the default branch.

2017-04-05 18:26 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +9. You will now see the 2 containers running for the master branch of your repository. Note the name of the containers is the same name you gave them as in the Docker compose file.
Uppercase "C" in Compose.

2017-04-05 18:26 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +11. Your master environment should be up! You can explore the environment using the URL, Terminal and Filebrowser.
File browser is two words.

2017-04-05 18:28 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +3. Ensure that the toggle on the top of the branch pop over is toggled on. This will ensure that branches are created as they appear on GitHub.
Popover is one word

2017-04-05 18:28 UTC, prafulrana commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +9. You will now see the 2 containers running for the master branch of your repository. Note the name of the containers is the same name you gave them as in the Docker compose file.
got it. thanks.

2017-04-05 18:28 UTC, runnabro commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +3. Find the repository where the compose file lives, and select it.
Uppercase "C" in compose.

2017-04-05 18:55 UTC, prafulrana commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +  ![GitHub Organization People]({{ site.baseurl }}/images/compose_config_composefile.png)
what should I do?

2017-04-06 00:05 UTC, tosih commented on docker-compose/_posts/2017-04-03-launching-your-first-environment.md
> +  ![GitHub Organization People]({{ site.baseurl }}/images/compose_config_composefile.png)
Those are used to describe what the image is. In case it doesn't load or whatever.

2017-04-06 17:45 UTC, tosih approved these changes

2017-04-06 17:46 UTC, merged