update search
Runnable/docs pull request #83
Opened 2017-06-20 22:34 UTC by runnabro

- **Remove jQuery dependency.**
- Refactor search popover.
- Fix search popover cutting off last result.
- Add border-radius to sidebar when stacked at smaller sizes.

2017-06-20 23:18 UTC, tosih reviewed
![image](https://user-images.githubusercontent.com/10872529/27360089-1bc9b570-55d4-11e7-8280-370501527c4a.png)

Noticed this, can we suppress the search suggestions? `autocomplete="off"`

2017-06-20 23:22 UTC, tosih requested changes

2017-06-20 23:22 UTC, tosih commented on _includes/search.html
>  <input placeholder="Search…" type="search" id="search" class="grid-block shrink search" spellcheck="false">
Can we add `autocomplete="off"`?

2017-06-21 00:13 UTC, taylordolan reviewed
^

2017-06-21 00:13 UTC, taylordolan commented on _includes/head.html
> -  <script src="{{ site.baseurl }}/js/jquery.min.js"></script>
You should remove the file too

2017-06-21 00:15 UTC, taylordolan approved these changes

2017-06-21 00:38 UTC, tosih approved these changes

2017-06-21 00:38 UTC, merged